# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-18 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='ammount',
            new_name='amount',
        ),
    ]
