# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-18 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20180518_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.AddField(
            model_name='item',
            name='buyer',
            field=models.CharField(default='fillin', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='user_buyong',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_of_products', to='first_app.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='user_selling',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='seller_of_products', to='first_app.User'),
            preserve_default=False,
        ),
    ]
